# Generated by Django 5.2.17 on 2026-08-31 18:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("comprobantes", "__first__"),
        ("empleados", "0001_initial"),
        ("entidades", "__first__"),
        ("productos", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolicitudCompra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(blank=True, max_length=20)),
                ("fecha", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("retirada", "Retirada"),
                            ("facturada", "Facturada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="pendiente",
                        max_length=12,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("modificado", models.DateTimeField(auto_now=True)),
                (
                    "entidad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes_compra",
                        to="entidades.entidad",
                        verbose_name="Proveedor",
                    ),
                ),
                (
                    "responsable_retiro",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes_como_responsable_retiro",
                        to="empleados.empleado",
                        verbose_name="Autorizado a retirar",
                    ),
                ),
                (
                    "solicitante",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="solicitudes_como_solicitante",
                        to="empleados.empleado",
                        verbose_name="Solicitante (autoriza el pedido)",
                    ),
                ),
            ],
            options={
                "db_table": "solicitud_compra",
                "ordering": ["-fecha", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SolicitudCompraRenglon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cantidad", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "unidad_medida",
                    models.CharField(
                        blank=True,
                        default="Unidad",
                        max_length=45,
                        verbose_name="Formato",
                    ),
                ),
                ("descripcion", models.CharField(max_length=255)),
                (
                    "producto_sugerido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="renglones_solicitud_compra",
                        to="productos.productodetalle",
                        verbose_name="Producto de catálogo (si ya se sabe con qué coincide)",
                    ),
                ),
                (
                    "solicitud",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="renglones",
                        to="solicitudes_compra.solicitudcompra",
                    ),
                ),
            ],
            options={
                "db_table": "solicitud_compra_renglon",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SolicitudCompraRenglonComprobanteRenglon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                (
                    "comprobante_renglon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos_solicitud_compra",
                        to="comprobantes.comprobanterenglon",
                    ),
                ),
                (
                    "solicitud_renglon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vinculos",
                        to="solicitudes_compra.solicitudcomprarenglon",
                    ),
                ),
            ],
            options={
                "db_table": "solicitud_compra_renglon_comprobante_renglon",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("solicitud_renglon", "comprobante_renglon"),
                        name="unique_vinculo_solicitud_renglon_comprobante_renglon",
                    )
                ],
            },
        ),
    ]
