# Generated by Django 5.2.8 on 2026-09-18 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0009_seed_tipos_entidad_empleado'),
        ('solicitudes_compra', '0004_solicitud_creado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcompra',
            name='responsable_retiro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_como_responsable_retiro', to='entidades.entidad', verbose_name='Autorizado a retirar'),
        ),
        migrations.AlterField(
            model_name='solicitudcompra',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_como_solicitante', to='entidades.entidad', verbose_name='Solicitante (autoriza el pedido)'),
        ),
    ]
