# Generated by Django 5.2.8 on 2026-09-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_compra', '0006_producto_generico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productogenerico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
