# Generated by Django 5.2.8 on 2026-09-21 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_compra', '0009_fix_renglon_prioridad_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudcomprarenglon',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('retirada', 'Retirada'), ('facturada', 'Facturada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=12, verbose_name='Estado'),
        ),
    ]
