# Generated by Django 5.2.8 on 2026-09-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes_compra', '0010_solicitudcomprarenglon_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitudcompra',
            name='numero',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Número'),
        ),
    ]
