# Generated by Django 5.2.8 on 2026-08-24 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsientoContable',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('detalle', models.CharField(blank=True, max_length=245, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('id_cuenta_contable', models.IntegerField(blank=True, null=True)),
                ('acumulador', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('es_debe', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'asiento_contable',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BancoCuentaEntidad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_producto_tipo', models.IntegerField(blank=True, null=True)),
                ('cbu', models.CharField(blank=True, max_length=30, null=True)),
                ('numero', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'banco_cuenta_entidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BancoCuentaTipo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=145, null=True)),
            ],
            options={
                'db_table': 'banco_cuenta_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BancoCuentaTipoMovim',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=145, null=True)),
            ],
            options={
                'db_table': 'bancocuenta_tipomovim',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BancoSucursal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_banco', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=145, null=True)),
                ('codigo', models.CharField(blank=True, max_length=3, null=True)),
                ('id_ciudad', models.IntegerField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=145, null=True)),
            ],
            options={
                'db_table': 'banco_sucursal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Caja',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.FloatField(blank=True, null=True)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'bancocuenta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LibroCaja',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
                ('saldo_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'banco_cuenta_libro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoCaja',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('emision', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=20)),
                ('efectivizacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movimiento_caja',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoCajaConceptoTipo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=145, null=True)),
            ],
            options={
                'db_table': 'movimiento_caja_concepto_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoCajaBancoCuentaEntidad',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='movimientos_caja.movimientocaja')),
                ('numero_cuenta_entidad_destino', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'movimiento_caja_banco_cuenta_entidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoCajaDiferido',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='movimientos_caja.movimientocaja')),
                ('diferido', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movimiento_caja_diferido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoCajaNumero',
            fields=[
                ('movimiento_caja', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rel_numero', serialize=False, to='movimientos_caja.movimientocaja')),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'movimiento_caja_numero',
            },
        ),
        migrations.CreateModel(
            name='LibroMovim',
            fields=[
                ('movimiento_caja', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='asiento_libro', serialize=False, to='movimientos_caja.movimientocaja')),
                ('hoja', models.IntegerField(blank=True, null=True, verbose_name='Número de Hoja')),
                ('renglon', models.IntegerField(blank=True, null=True, verbose_name='Número de Renglón')),
                ('libro', models.ForeignKey(db_column='id_libro', on_delete=django.db.models.deletion.PROTECT, to='movimientos_caja.librocaja', verbose_name='Libro de Caja')),
            ],
            options={
                'db_table': 'bancocuentalibro_movim',
            },
        ),
        migrations.CreateModel(
            name='MovimientoCajaConcepto',
            fields=[
                ('movimiento_caja', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='rel_concepto', serialize=False, to='movimientos_caja.movimientocaja')),
                ('concepto_tipo', models.ForeignKey(db_column='id_concepto', on_delete=django.db.models.deletion.PROTECT, related_name='movimiento_caja_concepto', to='movimientos_caja.movimientocajaconceptotipo')),
            ],
            options={
                'db_table': 'movimiento_caja_concepto',
            },
        ),
        migrations.CreateModel(
            name='MovimientoCajaEmisor',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='emisor_relacion', serialize=False, to='movimientos_caja.movimientocaja')),
                ('id_entidad', models.ForeignKey(blank=True, db_column='id_entidad', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimiento_caja_emisor', to='entidades.entidad')),
            ],
            options={
                'db_table': 'movimiento_caja_emisor',
            },
        ),
    ]
