# Generated by Django 5.2.8 on 2026-09-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos_caja', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoTipo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=145, null=True)),
            ],
            options={
                'db_table': 'producto_tipo',
                'managed': False,
            },
        ),
    ]
