# Generated by Django 5.2.8 on 2026-09-30 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0003_seed_unidades_remitos'),
        ('cuenta_corriente_productos', '0002_comprobanterenglonmovimiento_cantidad_kg'),
        ('productos', '0002_itemtipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoEquivalenciaKg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_kg', models.DecimalField(decimal_places=4, help_text='Cuántos Kg equivale 1 unidad de esta unidad de medida para este producto (ej.: 8 si 1 Bolsa son 8kg).', max_digits=12, verbose_name='Kg por unidad')),
                ('guardado_el', models.DateTimeField(auto_now_add=True)),
                ('modificado_el', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalencias_kg', to='productos.productodetalle')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equivalencias_kg', to='comprobantes.comprobanteunidaddemedida', verbose_name='Unidad (no Kg)')),
            ],
            options={
                'verbose_name': 'equivalencia de unidad a Kg',
                'verbose_name_plural': 'equivalencias de unidades a Kg',
                'db_table': 'cta_cte_producto_equivalencia_kg',
                'ordering': ['producto__nombre', 'unidad__nombre'],
                'constraints': [models.UniqueConstraint(fields=('producto', 'unidad'), name='cta_cte_producto_unidad_equivalencia_unica')],
            },
        ),
    ]
