"""
Django settings for fontana_movimientos project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import environ
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    # set casting and default values
    DEBUG=(bool, False)
)

# Read the .env file
environ.Env.read_env(BASE_DIR / '.env')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
DEBUG = env('DEBUG')
ALLOWED_HOSTS = env.list('DJANGO_ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'productos',
    'entidades',
    'empleados',
    'movimientos',
    'django_select2',
    'comprobantes',
    'movimientos_caja',
    'retenciones',
    'retenciones_inym',
    'liquidaciones',
    'solicitudes_compra',
    'respaldo',
    'tipos',
    'remitos',


]

# Id de la entidad "Fontana S.A." (la empresa), usado por varias apps para
# saber cuál de las dos partes de un comprobante/remito es la propia (ver
# comprobantes.views.ENTIDAD_PROPIA_ID, liquidaciones.views.ENTIDAD_PROPIA_ID,
# movimientos_caja.views.ENTIDAD_PROPIA_ID y remitos.views/forms). Antes cada
# app tenía este mismo valor repetido como constante local; queda acá
# también, centralizado, para que remitos (nuevo) lo lea de settings en vez
# de sumar una constante más hardcodeada.
ENTIDAD_PROPIA_ID = 100

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Sirve los archivos estáticos propios del proyecto (CSS/JS), comprimidos.
    # Hace falta porque en producción corremos con waitress, que a diferencia
    # de "manage.py runserver" en desarrollo no sirve estáticos por su
    # cuenta. Va justo después de SecurityMiddleware, como pide whitenoise.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    # Exige login para CUALQUIER vista del sitio, salvo las decoradas con
    # @login_not_required (ver fontana_movimientos/views.py: login_view). Un
    # usuario no logueado que intente entrar a cualquier URL es redirigido a
    # LOGIN_URL con "?next=<url original>", así que login_view debe respetar
    # ese "next" para volver a la página que se quería ver.
    'django.contrib.auth.middleware.LoginRequiredMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fontana_movimientos.urls'

# Vista a la que se redirige a quien no está logueado (ver arriba,
# LoginRequiredMiddleware). 'login' es el name de la URL, no una ruta fija,
# para que Django la resuelva sola aunque cambie de path en el futuro.
LOGIN_URL = 'login'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'fontana_movimientos.context_processors.entorno_bd',
                'fontana_movimientos.context_processors.permisos_menu',
                'tipos.context_processors.tipos_menu',
            ],
        },
    },
]

WSGI_APPLICATION = 'fontana_movimientos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
"""
DATA_UPLOAD_MAX_NUMBER_FIELDS = 3000  # O el valor que necesites


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [ os.path.join(BASE_DIR,'static') ]

STATIC_ROOT = os.path.join(BASE_DIR, 'assets')

# Almacenamiento que usa whitenoise para los estáticos: los sirve
# comprimidos (gzip), pero sin renombrarlos con hash (a diferencia de
# "ManifestStaticFilesStorage"), para no romper el "?v=4" a mano que ya se
# usa en base.html para forzar la actualización de caché del navegador.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
