# Generated by Django 5.2.8 on 2026-08-24 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_cuenta', models.IntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('neto_gravado', models.FloatField(blank=True, null=True)),
                ('recargo', models.FloatField(blank=True, null=True)),
                ('impuesto', models.FloatField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('entidad_nombre', models.CharField(blank=True, max_length=345, null=True)),
                ('comprobante_string', models.CharField(blank=True, max_length=145, null=True)),
                ('punto_de_venta', models.IntegerField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('otros_tributos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exento', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('agregado_desde', models.CharField(blank=True, max_length=45, null=True)),
                ('es_emisor', models.IntegerField(blank=True, null=True)),
                ('moneda', models.CharField(blank=True, max_length=4, null=True)),
                ('neto_no_gravado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('fecha_contabilizacion', models.DateField(blank=True, null=True)),
                ('iva', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('detalle', models.CharField(blank=True, max_length=345, null=True)),
                ('numero_hasta', models.IntegerField(blank=True, null=True)),
                ('codigo_autorizacion', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comprobante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComprobanteRenglon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('comprobante', models.OneToOneField(db_column='id_comprobante', on_delete=django.db.models.deletion.CASCADE, parent_link=True, related_name='renglon_comprobante', to='comprobantes.comprobante')),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('id_cuenta_contable', models.IntegerField(blank=True, null=True)),
                ('id_asiento_contable', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comprobante_renglon',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComprobanteTipo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=145, null=True)),
                ('id_afip', models.CharField(max_length=45, null=True)),
                ('abreviatura', models.CharField(blank=True, max_length=6, null=True)),
            ],
            options={
                'db_table': 'comprobante_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComprobanteUnidadDeMedida',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'comprobante_unidad_de_medida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentoTipo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'documento_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='IvaTipo',
            fields=[
                ('id_afip', models.IntegerField(blank=True, null=True)),
                ('producto', models.OneToOneField(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='producto_iva_tipo', serialize=False, to='productos.productodetalle')),
            ],
            options={
                'db_table': 'iva_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SectorTipo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=145, null=True)),
            ],
            options={
                'db_table': 'sector_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComprobanteRenglonDetalle',
            fields=[
                ('comprobante_renglon', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='renglon_detalle_comprobante', serialize=False, to='comprobantes.comprobanterenglon')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('bonificacion', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('id_iva_tipo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comprobante_renglon_detalle',
                'managed': False,
            },
        ),
    ]
