# Generated by Django 5.2.8 on 2026-09-04 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteTipoDeCambio',
            fields=[
                ('comprobante', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tipo_de_cambio', serialize=False, to='comprobantes.comprobante')),
                ('tipo_de_cambio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'comprobante_tipo_de_cambio',
                'managed': False,
            },
        ),
    ]
