# Generated by Django 5.2.8 on 2026-09-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BancoCuentaTipoProducto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'banco_cuenta_tipo_producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuentaTipo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=245, null=True)),
            ],
            options={
                'db_table': 'cuenta_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ProductoTipo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=145, null=True)),
            ],
            options={
                'db_table': 'producto_tipo',
                'managed': False,
            },
        ),
    ]
