# Generated by Django 5.2.8 on 2026-09-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Retencion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('entidad_nombre', models.CharField(blank=True, max_length=345, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('porcentaje', models.FloatField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('comprobante_string', models.CharField(blank=True, max_length=425, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('tipo_comp_origen', models.IntegerField(blank=True, null=True)),
                ('comprobante_origen', models.CharField(blank=True, max_length=145, null=True)),
                ('fecha_comp_origen', models.DateField(blank=True, null=True)),
                ('monto_comp_origen', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('id_condicion', models.IntegerField(blank=True, null=True)),
                ('porcentaje_exclusion', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tipo_doc_entidad', models.IntegerField(blank=True, null=True)),
                ('id_operacion', models.IntegerField(blank=True, null=True)),
                ('numero_certificado_afip', models.CharField(blank=True, max_length=45, null=True)),
                ('agregado_desde', models.CharField(blank=True, max_length=145, null=True)),
                ('año', models.IntegerField(blank=True, null=True, verbose_name='año')),
                ('numero', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'retencion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetencionTipoImpuesto',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=145, null=True)),
            ],
            options={
                'db_table': 'retencion_tipo_impuesto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetencionTipoRegimen',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=445, null=True)),
            ],
            options={
                'db_table': 'retencion_tipo_regimen',
                'managed': False,
            },
        ),
    ]
