# Generated by Django 5.2.8 on 2026-09-22 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retenciones', '0002_retencion_es_emisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetencionRegimenImpuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impuesto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_regimen', to='retenciones.retenciontipoimpuesto')),
                ('regimen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_impuesto', to='retenciones.retenciontiporegimen')),
            ],
            options={
                'db_table': 'retencion_regimen_impuesto',
                'constraints': [models.UniqueConstraint(fields=('regimen', 'impuesto'), name='unico_regimen_impuesto')],
            },
        ),
    ]
