# Generated by Django 5.2.8 on 2026-09-22 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0003_seed_unidades_remitos'),
        ('retenciones', '0003_retencionregimenimpuesto'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetencionRenglon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neto_gravado', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('porcentaje', models.FloatField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retencion_renglones', to='comprobantes.comprobante')),
                ('retencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renglones', to='retenciones.retencion')),
            ],
            options={
                'db_table': 'retencion_renglon',
                'constraints': [models.UniqueConstraint(fields=('retencion', 'comprobante'), name='unico_retencion_comprobante')],
            },
        ),
    ]
