# Generated by Django 5.2.8 on 2026-09-22 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comprobantes', '0003_seed_unidades_remitos'),
        ('retenciones', '0004_retencionrenglon'),
    ]

    operations = [
        migrations.AddField(
            model_name='retencionrenglon',
            name='id_impuesto',
            field=models.ForeignKey(db_column='id_impuesto', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='retenciones.retenciontipoimpuesto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='retencionrenglon',
            name='id_regimen',
            field=models.ForeignKey(db_column='id_regimen', default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='retenciones.retenciontiporegimen'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='retencionrenglon',
            constraint=models.UniqueConstraint(fields=('comprobante', 'id_impuesto', 'id_regimen'), name='unico_comprobante_impuesto_regimen'),
        ),
    ]
