# Generated by Django 5.2.8 on 2026-09-29 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('retenciones', '0005_retencionrenglon_id_impuesto_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='retencionrenglon',
            name='unico_comprobante_impuesto_regimen',
        ),
    ]
