# Generated by Django 5.2.8 on 2026-09-06 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('comprobantes', '0002_comprobantetipodecambio'),
        ('entidades', '0008_grupo_remitos'),
        ('movimientos', '0002_delete_comprobanteunidaddemedida_and_more'),
        ('productos', '0002_itemtipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acoplado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'acoplado',
                'verbose_name_plural': 'acoplados',
                'db_table': 'remito_acoplado',
                'ordering': ['patente'],
            },
        ),
        migrations.CreateModel(
            name='CondicionVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'condición de venta',
                'verbose_name_plural': 'condiciones de venta',
                'db_table': 'remito_condicion_venta',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ObservacionEstandar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=500, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'observación estándar',
                'verbose_name_plural': 'observaciones estándar',
                'db_table': 'remito_observacion_estandar',
                'ordering': ['texto'],
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('patente', models.CharField(max_length=20, unique=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'vehículo',
                'verbose_name_plural': 'vehículos',
                'db_table': 'remito_vehiculo',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Remito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('salida', 'Salida (Fontana emite el remito)'), ('entrada', 'Entrada (Fontana recibe el remito)')], default='salida', max_length=10)),
                ('punto_venta', models.PositiveIntegerField(verbose_name='Punto de venta')),
                ('numero', models.PositiveIntegerField(verbose_name='Número')),
                ('fecha', models.DateField()),
                ('valor_declarado', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Valor declarado')),
                ('observaciones', models.TextField(blank=True)),
                ('guardado_el', models.DateTimeField(auto_now_add=True)),
                ('modificado_el', models.DateTimeField(auto_now=True, verbose_name='fecha de edición')),
                ('acoplado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remitos', to='remitos.acoplado')),
                ('chofer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remitos_como_chofer', to='entidades.entidad')),
                ('condicion_venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remitos', to='remitos.condicionventa')),
                ('emisor', models.ForeignKey(db_column='id_entidad_emisor', on_delete=django.db.models.deletion.PROTECT, related_name='remitos_emitidos', to='entidades.entidad')),
                ('receptor', models.ForeignKey(db_column='id_entidad_receptor', on_delete=django.db.models.deletion.PROTECT, related_name='remitos_recibidos', to='entidades.entidad')),
                ('transportista', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remitos_como_transportista', to='entidades.entidad')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remitos', to='remitos.vehiculo')),
            ],
            options={
                'db_table': 'remito',
                'ordering': ['-fecha', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RemitoRenglon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField(default=1)),
                ('detalle_adicional', models.CharField(blank=True, help_text='Aclaración libre sobre este renglón (ej. lote, calidad, etc.).', max_length=200, verbose_name='Detalle adicional')),
                ('cantidad', models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad de bultos/unidades (ej. cantidad de bolsas), si corresponde.', max_digits=12, null=True, verbose_name='Cantidad')),
                ('kilogramos_enviados', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Kg. enviados')),
                ('kilogramos_confirmados', models.DecimalField(blank=True, decimal_places=2, help_text='Completar cuando se sepa el peso real recibido/facturado en destino, si difiere del enviado.', max_digits=12, null=True, verbose_name='Kg. confirmados en destino')),
                ('movimiento', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renglon_remito', to='movimientos.movimiento')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renglones_remito', to='productos.productodetalle')),
                ('remito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renglones', to='remitos.remito')),
                ('unidad_de_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renglones_remito', to='comprobantes.comprobanteunidaddemedida')),
            ],
            options={
                'verbose_name': 'renglón de remito',
                'verbose_name_plural': 'renglones de remito',
                'db_table': 'remito_renglon',
                'ordering': ['remito', 'orden', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='remito',
            constraint=models.UniqueConstraint(fields=('emisor', 'punto_venta', 'numero'), name='remito_unico_por_emisor'),
        ),
    ]
