# Generated by Django 5.2.8 on 2026-09-07 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remitos', '0002_seed_condicion_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculo',
            name='acoplados_habituales',
            field=models.ManyToManyField(blank=True, related_name='vehiculos_habituales', to='remitos.acoplado', verbose_name='Acoplados habituales'),
        ),
    ]
