# Generated by Django 5.2.8 on 2026-06-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entidad',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=105, null=True)),
                ('cuit', models.CharField(blank=True, max_length=45, null=True)),
                ('direccion', models.CharField(blank=True, max_length=145, null=True)),
                ('documento_nro', models.IntegerField(blank=True, null=True)),
                ('codigo', models.IntegerField(blank=True, null=True)),
                ('localidad', models.CharField(blank=True, max_length=145, null=True)),
                ('codpos', models.CharField(blank=True, max_length=45, null=True)),
                ('iva', models.CharField(blank=True, max_length=45, null=True)),
                ('provincia', models.CharField(blank=True, max_length=145, null=True)),
            ],
            options={
                'db_table': 'entidad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inym_Operador',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'inym_operador',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inym_Operador_Tipo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=105, null=True)),
            ],
            options={
                'db_table': 'inym_operador_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name_plural': 'roles',
                'db_table': 'rol_entidad',
                'managed': True,
            },
        ),
    ]
