# Generated by Django 5.2.8 on 2026-06-11 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entidades', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprobanteUnidadDeMedida',
            fields=[
                ('id', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'comprobante_unidad_de_medida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id_movimiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('guardado_el', models.DateTimeField(auto_now_add=True)),
                ('modificado_el', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de edición')),
            ],
            options={
                'db_table': 'movimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MovimientoPesaje',
            fields=[
                ('movimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movimientos.movimiento')),
                ('bruto', models.FloatField(blank=True, null=True)),
                ('tara', models.FloatField(blank=True, null=True)),
                ('descuento', models.FloatField(blank=True, null=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('hora_ingreso', models.TimeField(blank=True, null=True)),
                ('hora_salida', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'movimiento_pesaje',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MovimientoHvYerbaMate',
            fields=[
                ('movimiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='movimientos.movimiento')),
                ('inym_operador_destino', models.ForeignKey(blank=True, db_column='id_inym_operador_destino', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inym_operador_destino', to='entidades.inym_operador')),
                ('inym_operador_origen', models.ForeignKey(blank=True, db_column='id_inym_operador_origen', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='inym_operador_origen', to='entidades.inym_operador')),
            ],
            options={
                'db_table': 'movimiento_hv_yerba_mate',
                'managed': True,
            },
            bases=('movimientos.movimiento',),
        ),
    ]
