# Generated by Django 5.2.8 on 2026-08-24 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ComprobanteUnidadDeMedida',
        ),
        migrations.AlterField(
            model_name='movimientopesaje',
            name='movimiento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='movimiento_pesaje', serialize=False, to='movimientos.movimiento'),
        ),
    ]
