# Generated by Django 5.2.8 on 2026-06-10 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoDetalle',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=145, null=True)),
                ('id_item_tipo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'producto_detalle',
                'managed': False,
            },
        ),
    ]
