# Generated by Django 5.2.8 on 2026-09-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InymRetencionTipo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=145, null=True)),
            ],
            options={
                'db_table': 'inym_retencion_tipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetencionInym',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('periodo', models.DateField(blank=True, null=True)),
                ('kgs', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('eliminacion', models.DateField(blank=True, null=True)),
                ('tarifa', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('agregado_desde', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'retencion_inym',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetencionInymNoAplicacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('id_certificado_inym_no_aplicacion', models.IntegerField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'retencion_inym_no_aplicacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RetencionInymOrigen',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'retencion_inym_origen',
                'managed': False,
            },
        ),
    ]
