# Generated by Django 5.2.8 on 2026-09-24 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entidades', '0010_eliminar_grupo_empleados'),
        ('retenciones_inym', '0002_retencioninym_id_certificado_inym'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetencionInymHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('periodo', models.DateField(blank=True, null=True)),
                ('kgs', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('tarifa', models.DecimalField(blank=True, decimal_places=6, max_digits=20, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('id_certificado_inym', models.IntegerField(blank=True, null=True)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('id_tipo_tarifa', models.ForeignKey(db_column='id_tipo_tarifa', on_delete=django.db.models.deletion.PROTECT, to='retenciones_inym.inymretenciontipo')),
                ('operador_emisor', models.ForeignKey(blank=True, db_column='id_operador_emisor', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retencion_inym_historico_emisor_set', to='entidades.inym_operador')),
                ('operador_retenido', models.ForeignKey(blank=True, db_column='id_operador_retenido', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='retencion_inym_historico_retenido_set', to='entidades.inym_operador')),
            ],
            options={
                'db_table': 'retencion_inym_historico',
                'indexes': [models.Index(fields=['fecha'], name='retencion_i_fecha_a820af_idx'), models.Index(fields=['id_tipo_tarifa', 'fecha'], name='retencion_i_id_tipo_8ba727_idx')],
            },
        ),
    ]
