# Generated by Django 5.2.8 on 2026-09-04 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Liquidacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('numero', models.CharField(blank=True, max_length=145, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('debe', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('haber', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
            ],
            options={
                'db_table': 'liquidacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LiquidacionComprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'liquidacion_comprobante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LiquidacionMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'liquidacion_movimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LiquidacionRetencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'liquidacion_retencion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LiquidacionRetencionInym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'liquidacion_retencion_inym',
                'managed': False,
            },
        ),
    ]
